# this file is not designed to be run directly
# instead, use the docker-compose.<os>.<swift> files
# eg docker-compose -f docker/docker-compose.yaml -f docker/docker-compose.1804.50.yaml run test
version: "3"

services:

  test-setup:
    image: swiftly:default
    build:
      context: ..
      dockerfile: docker/test.dockerfile

  common: &common
    image: swiftly:default
    volumes:
      - ~/.ssh:/root/.ssh
      - ..:/code:z
    working_dir: /code
    cap_drop:
      - CAP_NET_RAW
      - CAP_NET_BIND_SERVICE

  lint:
    <<: *common
    image: swiftly:lint
    build:
      context: ..
      dockerfile: docker/lint.dockerfile
    command: /usr/bin/env bash -xcl "./scripts/check-lint.sh"

  test:
    <<: *common
    depends_on: [test-setup]
    command: /usr/bin/env bash -xcl "./scripts/run-tests.sh"

  install-test-setup:
    image: swiftly:install-default
    build:
      context: ..
      dockerfile: docker/install-test.dockerfile

  install-test-common: &install-test-common
    image: swiftly:install-default
    depends_on: [install-test-setup]
    volumes:
      - ~/.ssh:/root/.ssh
      - ../install:/swiftly-install:z
    working_dir: /swiftly-install
    cap_drop:
      - CAP_NET_RAW
      - CAP_NET_BIND_SERVICE

  install-test:
    <<: *install-test-common
    command: /usr/bin/env bash -xcl "./run-tests.sh"

  # util

  shell:
    <<: *common
    depends_on: [test-setup]
    entrypoint: /usr/bin/env bash
